package com.sync.syncroid_sftp.data.serverstorage

import androidx.room.Entity
import androidx.room.PrimaryKey
import java.util.Date

/**
 * Represents the data for a single SFTP server configuration stored in the local database.
 *
 * This data class is used as a Room [Entity] to persist server connection details.
 * It includes all necessary information to establish and manage an SFTP connection,
 * such as host, port, credentials, and default remote path.
 *
 * @property id The unique identifier for the server entry, auto-generated by the database.
 * @property name A user-defined name for the server configuration (e.g., "Work Server").
 * @property host The server's hostname or IP address.
 * @property port The port number for the SFTP connection (typically 22).
 * @property username The username for authentication.
 * @property password The password for authentication. TODO: This should be encrypted.
 * @property remotePath The default remote directory path to navigate to upon connection.
 * @property description An optional description for the server configuration.
 * @property createdAt The timestamp (in milliseconds) when this server entry was created.
 * @property updatedAt The timestamp (in milliseconds) when this server entry was last updated.
 */
@Entity(
    tableName = "servers_storage",
)
data class ServerStorage(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val name: String,
    val host: String,
    val port: Int,
    val username: String,
    val password: String,
    val remotePath: String,
    val description: String? = null,
    val fingerprint: String? = null,
    val createdAt: Long = Date().time,
    val updatedAt: Long? = null
) {

    init {
        val errors = buildList {
            if (name.isBlank()) add("Server name cannot be empty")
            if (host.isBlank()) add("Host cannot be empty")
            if (port !in 1..65535) add("Port must be between 1 and 65535")
            if (username.isBlank()) add("Username cannot be empty")
            if (password.isBlank()) add("Password cannot be empty")
            if (remotePath.isBlank()) add("Remote path cannot be empty")
        }

        // Throw an exception if there are validation errors
        require(errors.isEmpty()) {
            errors.joinToString("\n")
        }
    }
}
